"""Schedule sensitivity, and the guard that keeps it away from the card."""

import random

import pytest

from ti26.cli_schedule_sensitivity import spread
from ti26.montecarlo import category_marginals
from ti26.pairing import choose_pairing
from ti26.rules import load_rules
from ti26.types import Category

RULES = load_rules("config/ti2026_rules.yaml")
STRENGTHS = {f"t{i:02d}": 0.4 - 0.05 * i for i in range(16)}
TEAM_IDS = {t: str(1000 + i) for i, t in enumerate(sorted(STRENGTHS))}


def test_an_unset_preference_is_exactly_the_shipping_rule():
    """Kills mutation: let `preference=None` fall through to the random branch.

    This diagnostic added a parameter to code the card is generated by. If the
    default path drifts even slightly the shipping card changes as a side
    effect of a measurement, which is the one thing a diagnostic must never do.
    Equality here is exact, not approximate: same seed, same rule, same numbers.
    """
    without = category_marginals(STRENGTHS, RULES, n_sims=300, seed=7, team_ids=TEAM_IDS)
    explicit_none = category_marginals(
        STRENGTHS, RULES, n_sims=300, seed=7, team_ids=TEAM_IDS, pairing_preference=None
    )
    assert without == explicit_none


def test_the_preference_actually_reaches_the_pairing_engine():
    """Kills mutation: accept `pairing_preference` and never pass it down.

    A parameter that is threaded but ignored makes every variant identical to
    the baseline, which would report a sensitivity of zero and read as
    'the pairing rule does not matter' -- the exact conclusion this producer
    exists to test. Min and max must disagree somewhere.
    """
    low = category_marginals(
        STRENGTHS, RULES, n_sims=400, seed=3, team_ids=TEAM_IDS, pairing_preference="min"
    )
    high = category_marginals(
        STRENGTHS, RULES, n_sims=400, seed=3, team_ids=TEAM_IDS, pairing_preference="max"
    )
    assert low != high


def test_choose_pairing_honours_min_and_max_over_the_round_rule():
    """Kills mutation: apply `preference` only when maximize_distance is False.

    The round-5 elimination rule flips the engine to maximise. The variants
    have to override that too, or 'min' silently means 'min except where the
    rules already say max' and the comparison is not the one being reported.
    """
    members = ["a", "b", "c", "d"]
    rank_index = {"a": 0, "b": 1, "c": 2, "d": 3}
    prior: dict[str, set[str]] = {}

    def pick(preference, maximize):
        return {
            frozenset(p)
            for p in choose_pairing(
                members,
                rank_index,
                prior,
                random.Random(0),
                maximize_distance=maximize,
                preference=preference,
            ).matching
        }

    closest = {frozenset(("a", "b")), frozenset(("c", "d"))}
    assert pick("min", maximize=True) == closest, "min must override an elimination round"
    assert pick("max", maximize=False) != closest


def test_spread_measures_every_category_not_just_the_assigned_one():
    """Kills mutation: compute the spread over one category per team.

    A pairing rule can leave the argmax alone while moving the whole
    distribution underneath it. Summarising only the assigned slot would report
    no sensitivity for exactly the reshuffles that matter to a capacity-
    constrained assignment.
    """
    a = {"x": dict.fromkeys(Category, 0.0)}
    b = {"x": dict.fromkeys(Category, 0.0)}
    b["x"][Category.L0_4] = 0.5
    result = spread(a, b)
    assert result["max_abs_delta"] == pytest.approx(0.5)
    assert result["mean_abs_delta"] == pytest.approx(0.5 / len(Category))
